services:
  api:
    container_name: real-estate-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    restart: always
    networks:
      - app-network

  redis:
    container_name: real-estate-redis
    image: redis:7-alpine
    ports:
      - "6381:6379"
    restart: always
    networks:
      - app-network

  postgres:
    container_name: real-estate-postgres
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    container_name: real-estate-migrate
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: real-estate-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: real-estate-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network

  loki:
    image: grafana/loki:2.9.0
    container_name: real-estate-loki
    ports:
      - "3100:3100"
    networks:
      - app-network

  promtail:
    image: grafana/promtail:2.9.0
    container_name: real-estate-promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./monitoring/promtail.yml:/etc/promtail/promtail.yml
    depends_on:
      - loki
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
