"""add kyc and trust fields to users

Revision ID: 71eba41ae55c
Revises: 20260502_0002
Create Date: 2026-05-02 08:43:28.898562
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71eba41ae55c'
down_revision: Union[str, None] = '20260502_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenities_name'), 'amenities', ['name'], unique=True)
    op.create_table('badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('badge_type', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_name'), 'badges', ['name'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('builder_id', sa.String(length=36), nullable=False),
    sa.Column('rera_number', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('possession_date', sa.Date(), nullable=True),
    sa.Column('is_rera_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_builder_id'), 'projects', ['builder_id'], unique=False)
    op.create_index(op.f('ix_projects_rera_number'), 'projects', ['rera_number'], unique=True)
    op.create_table('trust_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('performed_by', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_audit_logs_entity_id'), 'trust_audit_logs', ['entity_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('badge_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badges')
    )
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('listed_by', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Enum('SALE', 'RENT', name='property_purpose'), nullable=False),
    sa.Column('property_type', sa.Enum('FLAT', 'HOUSE', 'VILLA', 'PLOT', 'LAND', 'COMMERCIAL', 'OFFICE', 'SHOP', name='property_type'), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('price_per_sqft', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_negotiable', sa.Boolean(), nullable=False),
    sa.Column('security_deposit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('maintenance_charge', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('area_sqft', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('carpet_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('builtup_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('plot_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('balconies', sa.Integer(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('facing', sa.String(length=50), nullable=True),
    sa.Column('age_of_property', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('furnishing', sa.Enum('FURNISHED', 'SEMI_FURNISHED', 'UNFURNISHED', name='furnishing_type'), nullable=True),
    sa.Column('parking', sa.Enum('NONE', 'BIKE', 'CAR', 'BOTH', name='parking_type'), nullable=True),
    sa.Column('water_supply', sa.String(length=100), nullable=True),
    sa.Column('power_backup', sa.Boolean(), nullable=False),
    sa.Column('gated_security', sa.Boolean(), nullable=False),
    sa.Column('lift', sa.Boolean(), nullable=False),
    sa.Column('gym', sa.Boolean(), nullable=False),
    sa.Column('swimming_pool', sa.Boolean(), nullable=False),
    sa.Column('garden', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('locality', sa.String(length=200), nullable=False),
    sa.Column('landmark', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('ownership_type', sa.String(length=100), nullable=True),
    sa.Column('property_documents_verified', sa.Boolean(), nullable=False),
    sa.Column('documents_verified', sa.Boolean(), nullable=False),
    sa.Column('rera_registered', sa.Boolean(), nullable=False),
    sa.Column('rera_number', sa.String(length=120), nullable=True),
    sa.Column('rera_state', sa.String(length=120), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('possession_date', sa.Date(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'UNDER_REVIEW', 'VERIFIED', 'APPROVED', 'REJECTED', 'SOLD', 'RENTED', name='property_status'), nullable=False),
    sa.Column('verification_status', sa.String(length=40), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('inquiries_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_properties_city', 'properties', ['city'], unique=False)
    op.create_index('ix_properties_price', 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_project_id'), 'properties', ['project_id'], unique=False)
    op.create_index('ix_properties_property_type', 'properties', ['property_type'], unique=False)
    op.create_index('ix_properties_purpose', 'properties', ['purpose'], unique=False)
    op.create_index(op.f('ix_properties_rera_number'), 'properties', ['rera_number'], unique=False)
    op.create_index(op.f('ix_properties_slug'), 'properties', ['slug'], unique=True)
    op.create_index('ix_properties_status', 'properties', ['status'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_favorites_user_property')
    )
    op.create_index(op.f('ix_favorites_property_id'), 'favorites', ['property_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_property_id'), 'inquiries', ['property_id'], unique=False)
    op.create_index(op.f('ix_inquiries_user_id'), 'inquiries', ['user_id'], unique=False)
    op.create_table('property_amenities',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('amenity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id', 'amenity_id')
    )
    op.create_table('property_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('performed_by', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_audit_logs_performed_by'), 'property_audit_logs', ['performed_by'], unique=False)
    op.create_index(op.f('ix_property_audit_logs_property_id'), 'property_audit_logs', ['property_id'], unique=False)
    op.create_table('property_badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('badge_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'badge_id', name='uq_property_badges')
    )
    op.create_index(op.f('ix_property_badges_badge_id'), 'property_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_property_badges_property_id'), 'property_badges', ['property_id'], unique=False)
    op.create_table('property_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.Enum('OWNERSHIP_PROOF', 'SALE_DEED', 'LAYOUT_PLAN', 'APPROVAL_CERTIFICATE', 'BUILDER_LICENSE', name='document_type'), nullable=False),
    sa.Column('file_url', sa.String(length=1200), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_documents_property_id'), 'property_documents', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_documents_uploaded_by'), 'property_documents', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_property_documents_verified_by'), 'property_documents', ['verified_by'], unique=False)
    op.create_table('property_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1200), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    op.add_column('users', sa.Column('kyc_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('kyc_type', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('kyc_document_url', sa.String(length=1200), nullable=True))
    op.add_column('users', sa.Column('kyc_verified_by', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_agent_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_company_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('trust_score', sa.Integer(), nullable=False))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_foreign_key(None, 'users', 'users', ['kyc_verified_by'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('users', 'trust_score')
    op.drop_column('users', 'is_company_verified')
    op.drop_column('users', 'is_agent_verified')
    op.drop_column('users', 'kyc_verified_at')
    op.drop_column('users', 'kyc_verified_by')
    op.drop_column('users', 'kyc_document_url')
    op.drop_column('users', 'kyc_type')
    op.drop_column('users', 'kyc_verified')
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_property_documents_verified_by'), table_name='property_documents')
    op.drop_index(op.f('ix_property_documents_uploaded_by'), table_name='property_documents')
    op.drop_index(op.f('ix_property_documents_property_id'), table_name='property_documents')
    op.drop_table('property_documents')
    op.drop_index(op.f('ix_property_badges_property_id'), table_name='property_badges')
    op.drop_index(op.f('ix_property_badges_badge_id'), table_name='property_badges')
    op.drop_table('property_badges')
    op.drop_index(op.f('ix_property_audit_logs_property_id'), table_name='property_audit_logs')
    op.drop_index(op.f('ix_property_audit_logs_performed_by'), table_name='property_audit_logs')
    op.drop_table('property_audit_logs')
    op.drop_table('property_amenities')
    op.drop_index(op.f('ix_inquiries_user_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_property_id'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_property_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_properties_status', table_name='properties')
    op.drop_index(op.f('ix_properties_slug'), table_name='properties')
    op.drop_index(op.f('ix_properties_rera_number'), table_name='properties')
    op.drop_index('ix_properties_purpose', table_name='properties')
    op.drop_index('ix_properties_property_type', table_name='properties')
    op.drop_index(op.f('ix_properties_project_id'), table_name='properties')
    op.drop_index('ix_properties_price', table_name='properties')
    op.drop_index('ix_properties_city', table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_trust_audit_logs_entity_id'), table_name='trust_audit_logs')
    op.drop_table('trust_audit_logs')
    op.drop_index(op.f('ix_projects_rera_number'), table_name='projects')
    op.drop_index(op.f('ix_projects_builder_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_badges_name'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_amenities_name'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
